import type { MetadataRoute } from "next";
import { getRequestContext } from "@cloudflare/next-on-pages";
import { POSTS_PER_PAGE, getTagIndex } from "@/lib/blog";
import { PRODUCTS, activeCategories } from "@/data/products";

export const runtime = "edge";

const siteUrl = "https://cybiqon.in";

/**
 * When the hand-written pages last actually changed. **Bump this when you edit one.**
 *
 * It used to be `new Date()` per entry, which meant all 20-odd marketing pages claimed
 * to have changed today, every day, forever — a signal a crawler learns to discount and
 * then ignores, taking the entries that *are* accurate down with it. A date that is
 * occasionally a few days stale is worth more than one that is always a lie.
 *
 * Deliberately a literal and not a build timestamp: a deploy that only touches /lab is
 * not a change to /pricing, and wiring it to the build would recreate the same problem
 * with extra steps.
 */
const STATIC_LAST_MODIFIED = new Date("2026-08-19T00:00:00Z");

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const staticPages: MetadataRoute.Sitemap = [
    { url: `${siteUrl}/`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 1.0 },
    { url: `${siteUrl}/about`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/our-works`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 0.85 },
    // "yearly" is honest: this changes when there is new press, not on a schedule.
    { url: `${siteUrl}/press`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "yearly", priority: 0.5 },
    { url: `${siteUrl}/pricing`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 0.9 },
    { url: `${siteUrl}/process`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "monthly", priority: 0.6 },
    { url: `${siteUrl}/case-studies`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 0.9 },
    { url: `${siteUrl}/rss.xml`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "daily", priority: 0.5 },
    { url: `${siteUrl}/blog`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "daily", priority: 0.9 },
    // /lab — hand-written, so weekly at most. Its own feed and author page.
    { url: `${siteUrl}/lab`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 0.7 },
    { url: `${siteUrl}/lab/about`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "yearly", priority: 0.4 },
    { url: `${siteUrl}/lab/rss.xml`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 0.3 },
    // Agent-readable surfaces. Static assets, generated by scripts/build-agent-markdown.mjs.
    { url: `${siteUrl}/llms.txt`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 0.3 },
    { url: `${siteUrl}/llms-full.txt`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 0.3 },
    { url: `${siteUrl}/faq`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "monthly", priority: 0.6 },
    { url: `${siteUrl}/free-audit`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/free-website`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "weekly", priority: 0.95 },
    { url: `${siteUrl}/contact`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/privacy`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "yearly", priority: 0.3 },
    { url: `${siteUrl}/terms`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "yearly", priority: 0.3 },
    { url: `${siteUrl}/products`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "monthly", priority: 0.7 },
    // Category pages, only for categories that actually have products.
    ...activeCategories().map((c) => ({
      url: `${siteUrl}/products/${c.slug}`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "monthly" as const, priority: 0.6,
    })),
    // Driven by data/products.ts — adding a product adds its three URLs automatically.
    ...PRODUCTS.flatMap((p) => [
      { url: `${siteUrl}/products/${p.slug}`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "monthly" as const, priority: 0.6 },
      { url: `${siteUrl}/products/${p.slug}/privacy`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "yearly" as const, priority: 0.3 },
      { url: `${siteUrl}/products/${p.slug}/terms`, lastModified: STATIC_LAST_MODIFIED, changeFrequency: "yearly" as const, priority: 0.3 },
    ]),
  ];

  let blogPages: MetadataRoute.Sitemap = [];
  let indexPages: MetadataRoute.Sitemap = [];
  let tagPages: MetadataRoute.Sitemap = [];
  let labPages: MetadataRoute.Sitemap = [];

  try {
    const { env } = getRequestContext();
    const { results } = await env.DB.prepare(
      "SELECT slug, created_at FROM blog_posts WHERE section = 'msme' AND published = 1 ORDER BY created_at DESC"
    ).all();

    const posts = results as { slug: string; created_at: string }[];
    const newest = posts.length ? new Date(posts[0].created_at) : new Date();

    blogPages = posts.map((post) => ({
      url: `${siteUrl}/blog/${post.slug}`,
      lastModified: new Date(post.created_at),
      changeFrequency: "monthly" as const,
      priority: 0.8,
    }));

    // Paginated index pages. /blog itself is already in staticPages, so start at 2.
    // These are listed so the crawler has the full set of index URLs up front rather
    // than having to walk rel="next" one hop at a time.
    const totalPages = Math.ceil(posts.length / POSTS_PER_PAGE);
    for (let p = 2; p <= totalPages; p++) {
      indexPages.push({
        url: `${siteUrl}/blog?page=${p}`,
        lastModified: newest,
        changeFrequency: "weekly" as const,
        priority: 0.4,
      });
    }

    const tags = await getTagIndex("msme");
    tagPages = tags.map((tag) => ({
      url: `${siteUrl}/blog/tag/${tag.slug}`,
      lastModified: newest,
      changeFrequency: "weekly" as const,
      priority: 0.6,
    }));

    // /lab posts. Separate query rather than one pass over both sections, because the
    // two produce different URL prefixes and different change frequencies — and a
    // single unscoped SELECT here is exactly how a lab post ends up advertised at
    // /blog/<slug>, which 404s.
    const labResults = await env.DB.prepare(
      `SELECT slug, created_at, updated_at FROM blog_posts
       WHERE section = 'lab' AND published = 1 ORDER BY created_at DESC`
    ).all();

    // updated_at when the post has been revised, created_at when it has not — the one
    // place a real lastModified is available rather than assumed. NULL means never
    // edited, so the fallback is a fact and not a guess.
    labPages = (
      labResults.results as {
        slug: string;
        created_at: string;
        updated_at: string | null;
      }[]
    ).flatMap((post) => {
      const lastModified = new Date(post.updated_at ?? post.created_at);
      return [
        {
          url: `${siteUrl}/lab/${post.slug}`,
          lastModified,
          changeFrequency: "monthly" as const,
          priority: 0.7,
        },
        // The markdown copy, so it is discoverable rather than only reachable through the
        // <link rel="alternate"> in the page head. Lower priority on purpose: it is an
        // alternate representation and the HTML is the canonical one.
        {
          url: `${siteUrl}/md/lab/${post.slug}.md`,
          lastModified,
          changeFrequency: "monthly" as const,
          priority: 0.3,
        },
      ];
    });
  } catch {
    // If DB is unavailable, return only static pages
  }

  return [...staticPages, ...blogPages, ...labPages, ...tagPages, ...indexPages];
}
